// <auto-generated />
using System;
using Chatbot.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chatbot.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329093721_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AIMemberProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedTools")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutonomous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgeScope")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibilitySummary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("ai_member_profiles", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ConciergeApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanHandoffPolicy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrimaryAiMemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceScope")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketCreationPolicy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryAiMemberId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ProjectId", "Name");

                    b.ToTable("concierge_apps", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConciergeAppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ConciergeAppId", "CreatedAt");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("conversation_messages", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternalSystemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSystemType", "ExternalId");

                    b.HasIndex("TeamId", "Email");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.IntegrationConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalSystemType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "ExternalSystemType", "Name")
                        .IsUnique();

                    b.ToTable("integration_connections", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "DisplayName");

                    b.HasIndex("TeamId", "UserId");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternalSystemType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LeadMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeadMemberId");

                    b.HasIndex("ExternalSystemType", "ExternalId");

                    b.HasIndex("TeamId", "Name");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedMemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConciergeAppId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternalSystemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMemberId");

                    b.HasIndex("ConciergeAppId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ExternalSystemType", "ExternalId");

                    b.HasIndex("ProjectId", "Status", "Priority");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AIMemberProfile", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "Member")
                        .WithOne("AiProfile")
                        .HasForeignKey("Chatbot.Api.Domain.Entities.AIMemberProfile", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ConciergeApp", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "PrimaryAiMember")
                        .WithMany()
                        .HasForeignKey("PrimaryAiMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Api.Domain.Entities.Project", "Project")
                        .WithMany("ConciergeApps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany("ConciergeApps")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryAiMember");

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.ConciergeApp", "ConciergeApp")
                        .WithMany("Conversations")
                        .HasForeignKey("ConciergeAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Customer", "Customer")
                        .WithMany("Conversations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConciergeApp");

                    b.Navigation("Customer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ConversationMessage", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conversation");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.IntegrationConnection", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany("IntegrationConnections")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Member", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Project", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "LeadMember")
                        .WithMany("LeadProjects")
                        .HasForeignKey("LeadMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeadMember");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Team", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.User", "OwnerUser")
                        .WithMany("OwnedTeams")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "AssignedMember")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.ConciergeApp", "ConciergeApp")
                        .WithMany()
                        .HasForeignKey("ConciergeAppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Tickets")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Project", "Project")
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedMember");

                    b.Navigation("ConciergeApp");

                    b.Navigation("Conversation");

                    b.Navigation("Customer");

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ConciergeApp", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Member", b =>
                {
                    b.Navigation("AiProfile");

                    b.Navigation("AssignedTickets");

                    b.Navigation("LeadProjects");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Project", b =>
                {
                    b.Navigation("ConciergeApps");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Team", b =>
                {
                    b.Navigation("ConciergeApps");

                    b.Navigation("IntegrationConnections");

                    b.Navigation("Members");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("OwnedTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
