// <auto-generated />
using System;
using Chatbot.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chatbot.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AIMemberProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedTools")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutableActions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutonomous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgeScope")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionBoundary")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibilitySummary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("ai_member_profiles", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AgentExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoundarySummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSummary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolCategory")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("WorkflowStepId", "ToolName");

                    b.ToTable("agent_execution_logs", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AgentWorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StartedByMemberId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryAttemptTrace")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryRawResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummarySchemaVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("StartedByMemberId");

                    b.HasIndex("TicketId");

                    b.HasIndex("TeamId", "Status", "WorkflowType");

                    b.HasIndex("TeamId", "TicketId", "CreatedAt");

                    b.ToTable("agent_workflow_runs", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AgentWorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HandoffSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HandoffToMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputAttemptTrace")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputRawResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchemaVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSummary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HandoffToMemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("WorkflowRunId", "Sequence")
                        .IsUnique();

                    b.ToTable("agent_workflow_steps", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AiMemberTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedTools")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutableActions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutonomous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgeScope")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionBoundary")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibilitySummary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("TeamId", "IsEnabled", "SortOrder");

                    b.ToTable("ai_member_templates", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionType", "CreatedAt");

                    b.HasIndex("TeamId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ConciergeApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessHours")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelLabel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaqScope")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanHandoffPolicy")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntakeGuidance")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrimaryAiMemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequirePhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceScope")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuggestedPrompts")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketCreationPolicy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WelcomeMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryAiMemberId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ProjectId", "Name");

                    b.ToTable("concierge_apps", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConciergeAppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ConciergeAppId", "CreatedAt");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("conversation_messages", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternalSystemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowUpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastContactedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLabel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ExternalSystemType", "ExternalId");

                    b.HasIndex("TeamId", "Email");

                    b.HasIndex("TeamId", "ProjectId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.IntegrationConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalSystemType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "ExternalSystemType", "Name")
                        .IsUnique();

                    b.ToTable("integration_connections", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "DisplayName");

                    b.HasIndex("TeamId", "UserId");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternalSystemType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LeadMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextSteps")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskSummary")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageLabel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeadMemberId");

                    b.HasIndex("ExternalSystemType", "ExternalId");

                    b.HasIndex("TeamId", "Name");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleLabel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProjectId", "MemberId")
                        .IsUnique();

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.TeamInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("Email");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("TeamId", "Email", "Status");

                    b.ToTable("team_invitations", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConciergeAppId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternalSystemType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionSummary")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMemberId");

                    b.HasIndex("ConciergeAppId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ExternalSystemType", "ExternalId");

                    b.HasIndex("ProjectId", "Status", "Priority");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.TicketActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActorMemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorMemberId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TicketId", "CreatedAt");

                    b.ToTable("ticket_activities", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AIMemberProfile", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "Member")
                        .WithOne("AiProfile")
                        .HasForeignKey("Chatbot.Api.Domain.Entities.AIMemberProfile", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AgentExecutionLog", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.AgentWorkflowStep", "WorkflowStep")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AgentWorkflowRun", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "StartedByMember")
                        .WithMany()
                        .HasForeignKey("StartedByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conversation");

                    b.Navigation("Project");

                    b.Navigation("RequestedByUser");

                    b.Navigation("StartedByMember");

                    b.Navigation("Team");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AgentWorkflowStep", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "HandoffToMember")
                        .WithMany()
                        .HasForeignKey("HandoffToMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.AgentWorkflowRun", "WorkflowRun")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HandoffToMember");

                    b.Navigation("Member");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AiMemberTemplate", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany("AiMemberTemplates")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ConciergeApp", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "PrimaryAiMember")
                        .WithMany()
                        .HasForeignKey("PrimaryAiMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Api.Domain.Entities.Project", "Project")
                        .WithMany("ConciergeApps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany("ConciergeApps")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryAiMember");

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.ConciergeApp", "ConciergeApp")
                        .WithMany("Conversations")
                        .HasForeignKey("ConciergeAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Customer", "Customer")
                        .WithMany("Conversations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConciergeApp");

                    b.Navigation("Customer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ConversationMessage", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conversation");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.IntegrationConnection", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany("IntegrationConnections")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Member", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Project", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "LeadMember")
                        .WithMany("LeadProjects")
                        .HasForeignKey("LeadMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeadMember");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "Member")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Team", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.User", "OwnerUser")
                        .WithMany("OwnedTeams")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.TeamInvitation", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.User", "AcceptedByUser")
                        .WithMany("AcceptedInvitations")
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chatbot.Api.Domain.Entities.User", "InvitedByUser")
                        .WithMany("SentInvitations")
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany("Invitations")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("InvitedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "AssignedMember")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.ConciergeApp", "ConciergeApp")
                        .WithMany()
                        .HasForeignKey("ConciergeAppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Tickets")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Project", "Project")
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedMember");

                    b.Navigation("ConciergeApp");

                    b.Navigation("Conversation");

                    b.Navigation("Customer");

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.TicketActivity", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.Member", "ActorMember")
                        .WithMany()
                        .HasForeignKey("ActorMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chatbot.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chatbot.Api.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Activities")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorMember");

                    b.Navigation("ActorUser");

                    b.Navigation("Team");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("Chatbot.Api.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AgentWorkflowRun", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.AgentWorkflowStep", b =>
                {
                    b.Navigation("ExecutionLogs");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.ConciergeApp", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Member", b =>
                {
                    b.Navigation("AiProfile");

                    b.Navigation("AssignedTickets");

                    b.Navigation("LeadProjects");

                    b.Navigation("ProjectMemberships");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Project", b =>
                {
                    b.Navigation("ConciergeApps");

                    b.Navigation("ProjectMembers");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Team", b =>
                {
                    b.Navigation("AiMemberTemplates");

                    b.Navigation("ConciergeApps");

                    b.Navigation("IntegrationConnections");

                    b.Navigation("Invitations");

                    b.Navigation("Members");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Chatbot.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("AcceptedInvitations");

                    b.Navigation("Memberships");

                    b.Navigation("OwnedTeams");

                    b.Navigation("SentInvitations");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
